version: '3.8'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: tips_php
    volumes:
      - ./www:/var/www/html
    networks:
      - tips-network
  web:
    image: nginx:alpine
    container_name: tips_nginx
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - tips-network
  db:
    image: mysql:8.0
    container_name: tips_mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tips_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tips-network
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: tips_mysql
    ports:
      - "1750:80"
    networks:
      - tips-network
networks:
  tips-network:
    driver: bridge
volumes:
  db_data:
